apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    env: dev
    component: catalogue
data:
  MONGO: "true" 
  MONGO_URL: "mongodb://mongodb:27017/catalogue"